### ISSUE TITLE
Upgrade Mimir API to Spark 3.2

### ISSUE THREAD

**Issue by sohampatel12** [VizierDB/vizier-scala#103]
After the release of Spark 3.2, change the package for the ImageType subclass of UDT.
Current package as a workaround: org.apache.spark.sql.types

**Comment by okennedy** [comment]
2.0 is updating to 3.2

**Comment by okennedy** [comment]
Closed with #147 

The ImageUDT workaround has been removed, and ImageUDT is now directly registered in `InitSpark`
