### ISSUE TITLE
Load Dataset defaults are confusing

### ISSUE THREAD

**Issue by lordpretzel** [VizierDB/vizier-scala#108]
The default for load dataset is to

- the file not have headers
- no type detection

However, I think more CSV files have headers than not. This will be very confusing to new users which do not know about the advanced options. It even happens to myself, I want to load a dataset and forget to set these options.

**Comment by okennedy** [comment]
Agreed.  This should be a quick change that won't break existing projects.  @mrb24 any arguments against rolling this into 1.1?

**Comment by okennedy** [comment]
Looks like the React code overrides the Load Dataset cell fields with hardcoded values.  Blorf.  I'll fix it there.

**Comment by okennedy** [comment]
I take it back.  The scala code wasn't reporting default values correctly to the frontend.  Fixed now.

**Comment by okennedy** [comment]
Somehow this change seems to have been reverted... It'll go into 1.1.1
