### ISSUE TITLE
Add an uploaded file manager

### ISSUE THREAD

**Issue by okennedy** [VizierDB/vizier-scala#119]
**Pain point:** Files uploaded (e.g., by being dragged onto the LOAD DATASET cell), or staged (e.g., an http URL in the LOAD DATASET cell) are present in the vizier.db folder, and available with artifact IDs, but are not visible to the user, and can not be re-used or accessed as artifacts.  If the user re-uploads a file, the uploaded or staged file is only relevant for history.

**Desiderata:**
1. Be able to select a previously uploaded file for use with LOAD DATASET
2. Be able to assign an uploaded file to a name so that it can be accessed by e.g., python cells.
3. Move staging to the LOAD DATASET UI (e.g., ask users to "download" an http url)
4. Be able to delete previously uploaded files

**Comment by okennedy** [comment]
Blocked on #154

**Comment by julianafreire** [comment]
Have you seen https://github.com/fatiando/pooch?
"manage a data registry by downloading your data files from a server only when needed and storing them locally in a data cache (a folder on your computer)."

**Comment by okennedy** [comment]
Nifty!  Vizier already does something similar --- with only a handful of exceptions, URLs generally get cached locally in the Vizier project folder.  It'd be nifty to add some extra reproducibility features (e.g., record an MD5 hash of the uploaded file, monitor the URL for changes, etc...)

**Comment by okennedy** [comment]
I had a bit of a deeper look at pooch.  It seems pretty comprehensive, and might address concerns with sharing data across projects.  It, or something like it should be incorporated into Vizier at some point (Broken out into #155 )

**Comment by okennedy** [comment]
Per discussions with @mrb24 , we're going to drop uploaded files from 2.0 (at least tentatively).
