### ISSUE TITLE
Recent versions of mill break builds.

### ISSUE THREAD

**Issue by okennedy** [VizierDB/vizier-scala#174]
**Describe the bug**
Compiling vizier with a recent mill fails

**To Reproduce**
`mill vizier.compile`

**Expected behavior**
everything should compile

**Screenshots**

```
[93/124] vizier.ui.fastOpt 
Found multiple public modules but module support is disabled: [main, out]
  exported to JavaScript with @JSExport
Linker: Compute reachability: 690054 us
Linker: 743346 us
1 targets failed
vizier.ui.fastOpt There were linking errors
```

This appears to be related to https://github.com/com-lihaoyi/mill/issues/1684

**Environment (please complete the following information):**
```
mill --version
Mill Build Tool version 0.10.2
Java version: 1.8.0\_292, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
Default locale: en\_US, platform encoding: UTF-8
OS name: "Mac OS X", version: 10.16, arch: x86\_64
```

**Comment by okennedy** [comment]
Report courtesy of @lordpretzel

**Comment by mrb24** [comment]
Mill 0.10.1 is the mill version that breaks.  Version 0.10.0 works.

**Comment by lolgab** [comment]
The following PR should fix the problem:
https://github.com/com-lihaoyi/mill/pull/1851

**Comment by okennedy** [comment]
Thanks @lolgab !

**Comment by lolgab** [comment]
Mill `0.10.3-36-e038bb` contains the fix. Can you try to see if it solves your problem?

**Comment by mrb24** [comment]
> Reference in new issue

Indeed, Mill 0.10.3-36-e038bb does fix our problem.  Thanks!
