### ISSUE TITLE
Clean up "New" module UX

### ISSUE THREAD

**Issue by okennedy** [VizierDB/vizier-scala#191]
To be discussed.  How do we want to lay it out?

**Comment by okennedy** [comment]
Significant improvements in 8a3a1e49fd824a0d8eca51bd4c4eca2bf6c0cab9

![image](https://github.com/VizierDB/vizier-scala/assets/3641553/0557148c-b2fa-4eba-a619-951f3a1daf9b)

**Comment by marysunc** [comment]
I like the idea of having picture and text as the UI. Users can have a quicker selection on the tool they want.
