### ISSUE TITLE
Chrome "access to localhost was denied"

### ISSUE THREAD

**Issue by okennedy** [VizierDB/vizier-scala#199]
**Describe the bug**
Loading Vizier in Chrome shows 
```
“Access to [localhost](http://localhost/) was denied”
```

**To Reproduce**
TBD

**Expected behavior**
The website opens in chrome

**Environment (please complete the following information):**

OS: OSX Monterey
Browser: Chrome
Java version: n/a
Vizier version: 2.0

**Additional context**
Reported by Emil Kovacev

Possibly a bug related to name resolution in Chrome when the computer is on an ipv6 network https://bugs.chromium.org/p/chromium/issues/detail?id=224215#c2

If that's the case, we should check for ipv6 and attempt to bind to `::1`

**Comment by okennedy** [comment]
That error suggests that you already have a running instance of Vizier.

**Comment by okennedy** [comment]
Additional bug: `-p` is being ignored.

**Comment by emilkovacev** [comment]
I was able to resolve this locally by updating the java v1.8 and using the port argument. It seems like Chrome reserves port 5000 (at least on Mac).

**Comment by okennedy** [comment]
It's odd that the request is coming from port 3001.  Any idea why that might be?

**Comment by emilkovacev** [comment]
I think 3001 was the option for -p that I set when running vizier.

**Comment by okennedy** [comment]
The localhost:5000 URL is hardcoded in the UI's `VIzier.scala`.  It's going to take some thought on how to get information about the URL into the frontend.  
- Modify `index.html` to include a dynamic component that dumps the URL into the system
- Add the public url to the service descriptor URL, and fetch that on boot.
- Infer the public facing URL from `window.url`

I think I'm leaning towards the last of those,,,
