### ISSUE TITLE
Documentation improvements - structure / organization

### ISSUE THREAD

**Issue by lordpretzel** [VizierDB/vizier-scala#2]
- add submenus for the wiki to organize topics hierarchically, e.g., [https://github.com/IITDBGroup/gprom/wiki](https://github.com/IITDBGroup/gprom/wiki). Some initial suggestion (to be discussed):
  - Overview & Concepts
  - Installation & Setup
  - Usage
  - Development
  - Cell Documentation
- pages that we may want to add:
  - API documentation
  - list of tutorials / how-tos (add over time for now the getting started one falls into this cateogry)
    - how to get data into Vizier
  - Vizier architecture (for developers and technical users that want to understand at a high-level of how Vizier works)
- home
  - possibly add a short description of what Vizier is

**Comment by okennedy** [comment]
As noted above, this appears to have been address.  Is it ok to close @lordpretzel ?
