### ISSUE TITLE
Troubling viewing an artifact

### ISSUE THREAD

**Issue by thomaseslowe** [VizierDB/vizier-scala#239]
I saved an artifact by the following code

vizierdb.save_data_frame('test1', df)

Then I clicked on the spreadsheet viewer button under Artifacts

It opened a new webpage and displayed what I suspect is the dataframe, but can't see it because it's fixed in size and is like 30 pixels wide

**Comment by okennedy** [comment]
I believe this got fixed a few updates ago.
