### ISSUE TITLE
insert module at top usually doesn't work, when clicking on the +

### ISSUE THREAD

**Issue by thomaseslowe** [VizierDB/vizier-scala#247]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

Docker Tag: [which docker image are you running]

**OR**

OS: [Put the output of `uname -a` here]
Browser: [e.g., firefox, safari, chrome]
Java version: [Put the output of `java -version` here]
Vizier version: [Put the output of `vizier --help | head -n 1` here]

**Additional context**

**Comment by okennedy** [comment]
Fixed by 5cd769267ace08da0b470e21406ddd50af861faa
