### ISSUE TITLE
Mill version 0.11.0 Compilation Error

### ISSUE THREAD

**Issue by shawnz99** [VizierDB/vizier-scala#260]
**Describe the bug**
When compiling vizier with mill version 0.11.0 using command `mill vizier.compile` it returns the following errors
```
[build.sc] [41/49] compile 
[info] compiling 1 Scala source to /home/shawnz99/src/school/research/vizier/vizier-scala/out/mill-build/compile.dest/classes ...
[error] /home/shawnz99/src/school/research/vizier/vizier-scala/build.sc:10:8: object Ctx is not a member of package mill.util
[error] import mill.util.Ctx
[error]        ^
[error] /home/shawnz99/src/school/research/vizier/vizier-scala/build.sc:156:13: not found: type Tests
[error]     extends Tests 
[error]             ^
[error] /home/shawnz99/src/school/research/vizier/vizier-scala/build.sc:242:25: not found: type Tests
[error]     object test extends Tests with TestModule.Utest {
[error]                         ^
[error] three errors found
1 targets failed
compile Compilation failed
```
However when compiling with mill version 0.10.10 it compiles fine with no errors

**To Reproduce**
1. Clone vizier
2. Make a branch off of the v2.0 branch
3. Install mill and ammonite (initially installed mill using coursier, then to revert the version easier I used a curl'd version of mill)
4. compile vizier using the command `mill vizier.compile`
5. See error

**Expected behavior**
Expected to compile with no errors 

**Screenshots**
![image](https://github.com/VizierDB/vizier-scala/assets/46944294/d421f244-5f0b-42ff-b21b-42314e355134)

**Environment (please complete the following information):**

OS: `Linux framework 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
Browser: opera
Java version: 
```
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing)
```
Vizier version: I'm using the cloned repo from a branch off of v2.0 branch

**Additional context**
I also got the error when I tried to set up bloop/metals
```
❯ mill mill.contrib.Bloop/install
[build.sc] [41/49] compile 
[info] compiling 1 Scala source to /home/shawnz99/src/school/research/vizier/vizier-scala/out/mill-build/compile.dest/classes ...
[error] /home/shawnz99/src/school/research/vizier/vizier-scala/build.sc:10:8: object Ctx is not a member of package mill.util
[error] import mill.util.Ctx
[error]        ^
[error] /home/shawnz99/src/school/research/vizier/vizier-scala/build.sc:156:13: not found: type Tests
[error]     extends Tests 
[error]             ^
[error] /home/shawnz99/src/school/research/vizier/vizier-scala/build.sc:242:25: not found: type Tests
[error]     object test extends Tests with TestModule.Utest {
[error]                         ^
[error] three errors found
1 targets failed
compile Compilation failed
```

**Comment by okennedy** [comment]
Closed by b7d5d08cd85b51d89c9556106080613eaa9a2eda
